- platform: mqtt
  name: "growbox_light"
  state_topic: "growbox/relay/light"
  command_topic: "growbox/relay/light/set"
  retain: true
- platform: mqtt
  name: "growbox_heater"
  state_topic: "growbox/relay/heater"
  command_topic: "growbox/relay/heater/set"
  retain: true
- platform: mqtt
  name: "growbox_fan"
  state_topic: "growbox/relay/fan"
  command_topic: "growbox/relay/fan/set"
  retain: true
- platform: mqtt
  name: "growbox_water"
  state_topic: "growbox/relay/water"
  command_topic: "growbox/relay/water/set"
  retain: true
