- platform: mqtt
  unique_id: growbox_light
  name: "Light"
  state_topic: "growbox/relay/light"
  command_topic: "growbox/relay/light/set"
  retain: true
- platform: mqtt
  unique_id: growbox_heater
  name: "Heater"
  state_topic: "growbox/relay/heater"
  command_topic: "growbox/relay/heater/set"
  retain: true
- platform: mqtt
  unique_id: growbox_fan
  name: "Fan"
  state_topic: "growbox/relay/fan"
  command_topic: "growbox/relay/fan/set"
  retain: true
- platform: mqtt
  unique_id: growbox_water
  name: "Water"
  state_topic: "growbox/relay/water"
  command_topic: "growbox/relay/water/set"
  retain: true
