- platform: template
  sensors:
    fibaro_error:
      value_template: >-
        {% if state_attr('persistent_notification.invalid_config', 'message') != None and 'fibaro' in state_attr('persistent_notification.invalid_config', 'message') %}
        Y
        {% else %}
        N
        {% endif %}
