- platform: mqtt
  name: "growbox_test"
  state_topic: "haha"
  json_attributes_topic: "haha"
  json_attributes_template: "{{ value_json | tojson }}"
- platform: mqtt
  name: "growbox_temperature"
  state_topic: "haha"
  unit_of_measurement: "°C"
  value_template: "{{ value_json.temperature }}"
- platform: mqtt
  name: "growbox_humidity"
  state_topic: "haha"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"
