- id: '1608817356789'
  alias: Growbox mqtt publish
  trigger:
    - platform: state
      entity_id: input_number.moisture_level
    - platform: state
      entity_id: input_number.temperature
    - platform: state
      entity_id: input_number.fan_duration_m
    - platform: state
      entity_id: input_number.fan_interval_h
    - platform: state
      entity_id: input_number.light_duration_h
    - platform: state
      entity_id: input_number.water_duration_s
  condition: [ ]
  action:
    - service: mqtt.publish
      data_template:
        topic: omfg
        retain: true
        payload_template: '{
        "moisture_level":"{{ states(''input_number.moisture_level'') }}",
        "temperature":"{{ states(''input_number.temperature'') }}",
        "fan_duration_m":"{{ states(''input_number.fan_duration_m'') }}",
        "fan_interval_h":"{{ states(''input_number.fan_interval_h'') }}",
        "light_duration_h":"{{ states(''input_number.light_duration_h'') }}",
        "water_duration_s":"{{ states(''input_number.water_duration_s'') }}"
        }'
  mode: single
- alias: 'Growbox turn on fan interval'
  trigger:
    - platform: time_pattern
      minutes: '/1'
  action:
    - service: switch.turn_on
      entity_id: switch.growbox_fan
    # - delay: "{{ states('input_number.fan_duration_m') | multiply(60) | int }}"
    - delay: "{{ states('input_number.fan_duration_m') | int }}"
    - service: switch.turn_off
      entity_id: switch.growbox_fan
- alias: 'Growbox turn on lights'
  trigger:
    - platform: time
      at: "6:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.growbox_light
- alias: 'Growbox turn off lights'
  trigger:
    - platform: time
      at: "22:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.growbox_light
- alias: 'Growbox turn off heater'
  trigger:
    - platform: numeric_state
      entity_id: sensor.growbox_temperature
      above: 21
      for: "00:00:10"
  action:
    - service: switch.off
      entity_id: switch.growbox_heater
- alias: 'Growbox turn on heater'
  trigger:
    - platform: numeric_state
      entity_id: sensor.growbox_temperature
      below: 21
  action:
    - service: switch.turn_on
      entity_id: switch.growbox_heater
- alias: 'Notify water level'
  trigger:
    - platform: numeric_state
      entity_id: sensor.growbox_water_level
      below: 1
  action:
    - service: notify.mobile_app_lukass_iphone
      data:
        message: "Growbox"
        title: "water level low pico"
