version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ../:/config
    environment:
      - TZ=Europe/Prague
    ports:
      - "8123:8123"
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9002:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mqtt/mosquitto.passwd:/mosquitto/config/mosquitto.passwd:ro
